name: Scrape and build

#on:
 # schedule:
  #  - cron: '0 3 * * *'
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Scrape votes
        run: python scraper.py votes

      - name: Scrape meetings
        run: python scraper.py meetings

      - name: Scrape moties
        run: python scraper.py moties

      - name: Scrape raadsvoorstellen
        run: python scraper.py raadsvoorstellen

      - name: Scrape amendementen
        run: python scraper.py amendementen

      - name: Scrape brieven
        run: python scraper.py brieven

      - name: Scrape vragen
        run: python scraper.py vragen

      - name: Download PDFs
        run: python scraper.py pdf

      - name: Download updates
        run: python scraper.py updates

      - name: Keyword analysis
        run: python scraper.py keywords

      - name: Generate HTML
        run: python build.py

      - name: Commit updated files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/ public/
          git diff --staged --quiet || git commit -m "Daily update $(date +'%Y-%m-%d')"
          git push
